Adds language file for Chinese
TownyAdvanced/TownyResources pull request #20
Opened 2021-09-04 16:57 UTC by Akiranya

2021-09-04 20:04 UTC, Goosius1 commented on src/main/resources/chinese.yml
> +author: Goosius
:construction: 
- Hi, do put your own name here :-)

2021-09-04 21:22 UTC, Goosius1 requested changes
1 comment

2021-09-05 02:53 UTC, Akiranya commented on src/main/resources/chinese.yml
> +author: Goosius
:3 done! also with some minor text improvement

2021-09-05 08:30 UTC, Goosius1 commented on src/main/resources/chinese.yml
> +
:construction: 
- Hi, just this morning, I added "slime" as a new resource category.
- For completeness of your file, could you add that translation also pls before we merge.

2021-09-05 11:34 UTC, Goosius1 commented on src/main/resources/chinese.yml
> +
I'm eager to get the (unrelated) slime fix out. So I'll say lets merge this now with just an english translation, and we can fix later

2021-09-05 11:35 UTC, Goosius1 approved these changes
Approved

2021-09-05 11:35 UTC, merged